FROM node:22-alpine AS build-stage

# install nginx
RUN apk add nginx

COPY frontend/nginx.conf /etc/nginx/nginx.conf

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

COPY locales ./src/locales

ENTRYPOINT [ "/bin/sh", "-c" ]

CMD ["npm run build && nginx -g 'daemon off;'"]

