FROM node:16-alpine AS build-stage

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

COPY .env .

COPY locales ./src/locales

RUN npm run build

FROM nginx AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/nginx.conf