services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db  
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - /data/db

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    env_file:
      - .env